#include <alice/alice.hpp>

#include "commands/compress.hpp"
#include "commands/cutrw.hpp"
#include "commands/refactor.hpp"
#include "commands/resub.hpp"
#include "commands/rewrite.hpp"
#include "commands/balance.hpp"
#include "commands/dm.hpp"
#include "commands/window_rewrite.hpp"
#include "commands/emap.hpp"
#include "commands/exact_map.hpp"
#include "commands/functional_reduction.hpp"
#include "commands/lut_mapping.hpp"
#include "commands/lut_maper.hpp"
#include "commands/lut_resyn.hpp"
#include "commands/techmap.hpp"
#include "commands/xmg_b.hpp"
#include "commands/xmg_rf.hpp"
#include "commands/xmg_rs.hpp"
#include "commands/xmg_rw.hpp"
#include "commands/xmgrw.hpp"
#include "store.hpp"

ALICE_MAIN(lsmap)
